import { Client, JobPost } from "./types";

export const MOCK_CLIENTS: Client[] = [
  {
    id: "c1",
    name: "Alice Freeman",
    email: "alice.f@example.com",
    position: "Frontend Engineer",
    status: "COMPLETED",
    interviewScore: 92,
    verdict: "STRONG_HIRE",
    lastUpdated: "2023-10-25T14:00:00Z",
  },
  {
    id: "c2",
    name: "Bob Chen",
    email: "bob.chen@example.com",
    position: "Backend Engineer",
    status: "IN_PROGRESS",
    lastUpdated: "2023-10-26T09:30:00Z",
    linkExpiresAt: "2023-10-29T09:30:00Z",
  },
  {
    id: "c3",
    name: "Charlie Davis",
    email: "charlie.d@example.com",
    position: "Product Designer",
    status: "NOT_STARTED",
    lastUpdated: "2023-10-27T10:00:00Z",
    linkExpiresAt: "2023-11-01T10:00:00Z",
  },
  {
    id: "c4",
    name: "Diana Evans",
    email: "diana.e@example.com",
    position: "Frontend Engineer",
    status: "EXPIRED",
    lastUpdated: "2023-10-20T11:00:00Z",
    linkExpiresAt: "2023-10-22T11:00:00Z",
  },
  {
    id: "c5",
    name: "Evan Wright",
    email: "evan.w@example.com",
    position: "DevOps Engineer",
    status: "COMPLETED",
    interviewScore: 78,
    verdict: "HIRE",
    lastUpdated: "2023-10-24T16:45:00Z",
  },
  {
    id: "c6",
    name: "Fiona Gallagher",
    email: "fiona.g@example.com",
    position: "Data Scientist",
    status: "COMPLETED",
    interviewScore: 45,
    verdict: "NO_HIRE",
    lastUpdated: "2023-10-23T13:20:00Z",
  },
  {
    id: "c7",
    name: "George Harris",
    email: "george.h@example.com",
    position: "Backend Engineer",
    status: "IN_PROGRESS",
    lastUpdated: "2023-10-26T15:00:00Z",
  },
  {
    id: "c8",
    name: "Hannah Kim",
    email: "hannah.k@example.com",
    position: "QA Engineer",
    status: "NOT_STARTED",
    lastUpdated: "2023-10-27T08:00:00Z",
  },
  {
    id: "c9",
    name: "Ian Lewis",
    email: "ian.l@example.com",
    position: "Frontend Engineer",
    status: "COMPLETED",
    interviewScore: 88,
    verdict: "HIRE",
    lastUpdated: "2023-10-25T11:30:00Z",
  },
  {
    id: "c10",
    name: "Jane Martinez",
    email: "jane.m@example.com",
    position: "Product Manager",
    status: "NOT_STARTED",
    lastUpdated: "2023-10-27T12:00:00Z",
  },
  {
    id: "c11",
    name: "Kyle Nelson",
    email: "kyle.n@example.com",
    position: "Backend Engineer",
    status: "COMPLETED",
    interviewScore: 95,
    verdict: "STRONG_HIRE",
    lastUpdated: "2023-10-22T09:00:00Z",
  },
  {
    id: "c12",
    name: "Liam O'Connor",
    email: "liam.o@example.com",
    position: "DevOps Engineer",
    status: "EXPIRED",
    lastUpdated: "2023-10-15T10:00:00Z",
  },
  {
    id: "c13",
    name: "Mia Peterson",
    email: "mia.p@example.com",
    position: "Data Analyst",
    status: "IN_PROGRESS",
    lastUpdated: "2023-10-26T14:15:00Z",
  },
  {
    id: "c14",
    name: "Noah Quinn",
    email: "noah.q@example.com",
    position: "Frontend Engineer",
    status: "COMPLETED",
    interviewScore: 62,
    verdict: "NO_HIRE",
    lastUpdated: "2023-10-21T16:00:00Z",
  },
  {
    id: "c15",
    name: "Olivia Roberts",
    email: "olivia.r@example.com",
    position: "HR Specialist",
    status: "NOT_STARTED",
    lastUpdated: "2023-10-27T09:45:00Z",
  },
];

export const MOCK_JOBS: JobPost[] = [
  {
    id: "j1",
    title: "Senior Frontend Engineer",
    location: "Remote",
    employmentType: "FULL_TIME",
    seniority: "SENIOR",
    status: "OPEN",
    createdAt: "2023-09-15T00:00:00Z",
    candidatesCount: 12,
    description: {
      intro: "We are looking for a Senior Frontend Engineer to lead our dashboard team.",
      responsibilities: ["Architect scalable UI components", "Mentor junior devs", "Optimize performance"],
      requirements: ["5+ years React", "TypeScript mastery", "Tailwind CSS"],
    },
  },
  {
    id: "j2",
    title: "Backend Engineer",
    location: "New York, NY",
    employmentType: "FULL_TIME",
    seniority: "MID",
    status: "OPEN",
    createdAt: "2023-10-01T00:00:00Z",
    candidatesCount: 8,
    description: {
      intro: "Join our core platform team building high-throughput APIs.",
      responsibilities: ["Design APIs", "Database optimization", "Microservices"],
      requirements: ["3+ years Node.js", "PostgreSQL", "AWS"],
    },
  },
  {
    id: "j3",
    title: "Product Designer",
    location: "San Francisco, CA",
    employmentType: "FULL_TIME",
    seniority: "MID",
    status: "OPEN",
    createdAt: "2023-10-05T00:00:00Z",
    candidatesCount: 5,
    description: {
      intro: "Help us shape the future of AI interviewing interfaces.",
      responsibilities: ["User research", "High-fidelity prototyping", "Design system"],
      requirements: ["Figma", "Prototyping", "Visual design skills"],
    },
  },
  {
    id: "j4",
    title: "DevOps Engineer",
    location: "Remote",
    employmentType: "CONTRACT",
    seniority: "SENIOR",
    status: "OPEN",
    createdAt: "2023-10-10T00:00:00Z",
    candidatesCount: 3,
    description: {
      intro: "Improve our CI/CD pipelines and infrastructure.",
      responsibilities: ["Manage Kubernetes", "Terraform", "Security audits"],
      requirements: ["AWS", "Docker", "CI/CD"],
    },
  },
  {
    id: "j5",
    title: "Data Scientist",
    location: "London, UK",
    employmentType: "FULL_TIME",
    seniority: "SENIOR",
    status: "CLOSED",
    createdAt: "2023-08-20T00:00:00Z",
    candidatesCount: 24,
    description: {
      intro: "Analyze interview data to improve our AI models.",
      responsibilities: ["Model training", "Data cleaning", "Algorithm design"],
      requirements: ["Python", "PyTorch/TensorFlow", "NLP"],
    },
  },
  {
    id: "j6",
    title: "QA Engineer",
    location: "Remote",
    employmentType: "PART_TIME",
    seniority: "JUNIOR",
    status: "OPEN",
    createdAt: "2023-10-12T00:00:00Z",
    candidatesCount: 1,
    description: {
      intro: "Ensure our platform is bug-free.",
      responsibilities: ["Manual testing", "Automated tests", "Bug reporting"],
      requirements: ["Cypress", "Detail oriented", "Communication"],
    },
  },
  {
    id: "j7",
    title: "Engineering Manager",
    location: "New York, NY",
    employmentType: "FULL_TIME",
    seniority: "SENIOR",
    status: "OPEN",
    createdAt: "2023-10-15T00:00:00Z",
    candidatesCount: 0,
    description: {
      intro: "Lead a team of 8 engineers.",
      responsibilities: ["People management", "Hiring", "Roadmap planning"],
      requirements: ["Previous management exp", "Technical background", "Empathy"],
    },
  },
  {
    id: "j8",
    title: "Marketing Specialist",
    location: "Remote",
    employmentType: "FULL_TIME",
    seniority: "MID",
    status: "CLOSED",
    createdAt: "2023-09-01T00:00:00Z",
    candidatesCount: 15,
    description: {
      intro: "Drive growth for our platform.",
      responsibilities: ["Content creation", "Social media", "Campaigns"],
      requirements: ["Copywriting", "SEO", "Analytics"],
    },
  },
];